### ISSUE TITLE
Vanilla 1.12

### ISSUE THREAD

**Issue by Busyatschool** [shagu/ShaguJunk#3]
Using this command:
/sjunk or /junk ls

Gives this error:
ERROR: Interface\AddOns\ShaguJunk\ShaguJunkj.lua:71: attempt to perform arithmetic on global 'printID' (a nil value).

![ShaguJunk Error 71](https://user-images.githubusercontent.com/89811414/131406369-9a3b4934-3cf8-4610-b92b-61bbc2c34999.png)

**Comment by shagu** [comment]
Thanks for your report. It is now fixed in the latest version by this commit: https://github.com/shagu/ShaguJunk/commit/3ff9d5f2afb318c58cb9c03afa18226dbf751341
